### PR TITLE
The initial migration of the CDI component specification EE integration requirements to the platform

### LINKED ISSUE #837: Migrate the CDI integration requirements from the CDI component project to the Platform project
As part of the EE 11 release plan, there was a desire to break up the CDI EE integration requirements and TCK to the platform. This issue is to track that migration effort.

- [ ] Migrate the CDI specification EE integration requirements to the Platform/Web Profile specifications
- [ ] Migrate the CDI integration TCK to the platform TCK as a new standalone TCK

### PR DESCRIPTION
**Pull request by starksm64**
This is a work in progress to incorporate the CDI specification EE integration requirements to the platform.

This PR appears to include several commits in order to preserve the history of the related content from the CDI specification repository.

One big issue to resolve with this is how to handle the cross references to the CDI specification that no longer resolve. (FIXED)

fixes #837

### CODE REVIEW

**Comment by starksm64** [comment]
The missing cross-references have been fixed by adding a xrefs.adoc section that points to the online CDI html specification sections.

**Comment by Emily-Jiang** [comment]
@starksm64 how can we deal with the ECA check failures?

**Comment by starksm64** [comment]
> @starksm64 how can we deal with the ECA check failures?

We can't because by pulling in the history the check is looking at CDI committers who are not platform committers. We know where this came from so we will just have to ignore the failures.

**Comment by edburns** [comment]
I have taken actions to rebase this PR onto `HEAD` of `main` in PR #855. I recommend closing this PR and treating #855 as subsuming this PR.

**Pull request closed without merging**
